name: build-luffy-golang-dev
run-name: ${{ github.actor }} is building go proram
on:
  push:
    branches:
      - 'luffy_dev'
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action@1.6.0
